apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: auth=auth-repo
    argocd-image-updater.argoproj.io/auth.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/auth.helm.image-name: image.name
    argocd-image-updater.argoproj.io/auth.helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/muhammadali792/Platform_repo
    targetRevision: main
    path: k8s-manifest/helm/microservice
    helm:
      valueFiles:
      - ../services/auth-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 
