apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notif-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/muhammadali792/Platform_repo
    targetRevision: main
    path: k8s-manifest/helm/microservice
    helm:
      valueFiles:
      - ../services/notif-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: notif
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 
