replicaCount: 2
image:
  registry: ""
  name: ""
  tag: ""

service:
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

migration:
  enabled: true
  command: ["npm", "run", "migrate"]

ingress:
  enabled: true
  host: auth.cloudaura.online
  port: 8000
  tls:
    enabled: true
  mtls:
    enabled: false
    secretName: auth-mtls-secret

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  cpuUtilization: 70

networkPolicy:
  enabled: true
  allowFrom:
    - order-service
  allowTo: []

rollout:
  enabled: true
  canary:
    autoRollback: true
    steps:
    - setWeight: 10
    - pause:
        duration: 60s
    - setWeight: 50
    - pause:
        duration: 60s
    - setWeight: 100

env:
  jwt:
    enabled: true
  db:
    enabled: true
  redis:
    enabled: false
