replicaCount: 2
image:
  name: order-repo
  registry: 351849325312.dkr.ecr.eu-north-1.amazonaws.com
  tag: latest
service:
  port: 8002

migration:
  enabled: true
  command: ["npm", "run", "migrate"]

ingress:
  enabled: true
  host: order.cloudaura.online
  port: 8002
  tls:
    enabled: true
  mtls:
    enabled: false
    secretName: order-mtls-secret

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 65

networkPolicy:
  enabled: true
  allowFrom:
    - product-service
  allowTo: []

rollout:
  enabled: true
  canary:
    autoRollback: true
    steps:
    - setWeight: 10
    - pause:
        duration: 60s
    - setWeight: 100

env:
  jwt:
    enabled: true
  db:
    enabled: true
  redis:
    enabled: true
