replicaCount: 2
image:
  name: product-repo
  registry: "351849325312.dkr.ecr.eu-north-1.amazonaws.com"
  tag: latest
service:
  port: 8001

migration:
  enabled: true
  command: ["npm", "run", "migrate"]

ingress:
  enabled: true
  host: product.cloudaura.online
  port: 8001
  tls:
    enabled: true
  mtls:
    enabled: false

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  cpuUtilization: 70

networkPolicy:
  enabled: true
  allowFrom:
    - order-service
  allowTo: []

rollout:
  enabled: true
  canary:
    autoRollback: true
    steps:
    - setWeight: 10
    - pause:
        duration: 60s
    - setWeight: 50
    - pause:
        duration: 60s
    - setWeight: 100

env:
  jwt:
    enabled: false
  db:
    enabled: true
  redis:
    enabled: true
