apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: microservices-updater
  namespace: argocd
spec:
  writeBackConfig:
    method: "git"
    gitConfig:
      repository: "git@github.com:muhammadali792/Platform_repo.git"
      branch: "main"
  applicationRefs:
  - namePattern: "auth-service"
    writeBackConfig:
      gitConfig:
        writeBackTarget: "helmvalues:../services/auth-values.yaml"
    images:
    - alias: "app"
      imageName: "351849325312.dkr.ecr.eu-north-1.amazonaws.com/auth-repo"
      commonUpdateSettings:
        updateStrategy: "digest"
      manifestTargets:
        helm:
          name: image.repository
          tag: image.tag

  - namePattern: "order-service"
    writeBackConfig:
      gitConfig:
        writeBackTarget: "helmvalues:../services/order-values.yaml"
    images:
    - alias: "app"
      imageName: "351849325312.dkr.ecr.eu-north-1.amazonaws.com/order-repo"
      commonUpdateSettings:
        updateStrategy: "digest"
      manifestTargets:
        helm:
          name: image.repository
          tag: image.tag

  - namePattern: "product-service"
    writeBackConfig:
      gitConfig:
        writeBackTarget: "helmvalues:../services/product-values.yaml"
    images:
    - alias: "app"
      imageName: "351849325312.dkr.ecr.eu-north-1.amazonaws.com/product-repo"
      commonUpdateSettings:
        updateStrategy: "digest"
      manifestTargets:
        helm:
          name: image.repository
          tag: image.tag

  - namePattern: "notif-service"
    writeBackConfig:
      gitConfig:
        writeBackTarget: "helmvalues:../services/notif-values.yaml"
    images:
    - alias: "app"
      imageName: "351849325312.dkr.ecr.eu-north-1.amazonaws.com/notif-repo"
      commonUpdateSettings:
        updateStrategy: "digest"
      manifestTargets:
        helm:
          name: image.repository
          tag: image.tag
