{{- if or .Values.env.jwt.enabled .Values.env.db.enabled .Values.env.redis.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
  data:
  {{- if .Values.env.jwt.enabled }}
  - secretKey: JWT_SECRET
    remoteRef:
      key: {{ .Release.Name }}-service/secrets
      property: JWT_SECRET
  {{- end }}
  {{- if .Values.env.db.enabled }}
  - secretKey: DATABASE_URL
    remoteRef:
      key: {{ .Release.Name }}-service/secrets
      property: DATABASE_URL
  {{- end }}
  {{- if .Values.env.redis.enabled }}
  - secretKey: REDIS_URL
    remoteRef:
      key: {{ .Release.Name }}-service/secrets
      property: REDIS_URL
  {{- end }}
{{- end }}
