name: Destroy Infrastructure

on:
  workflow_dispatch: # Sirf manual trigger par chalegi

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Cleanup Kubernetes Webhooks (Pre-destroy)
        run: |
          aws eks update-kubeconfig --name ${{ vars.CLUSTER_NAME }} --region us-east-1
          # Webhooks ko hatao jo Terraform ko "stuck" kar dete hain
          kubectl delete validatingwebhookconfigurations --all
          kubectl delete mutatingwebhookconfigurations --all

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
